class Staff {
  String? role;
  String? uid;
  String? password = '123456';
  String? department;
  String? designation;
  String? firstName;
  String? middleName;
  String? lastName;
  String? email;
  String? gender;
  String? dob;
  String? dateOfJoining;
  String? fatherName;
  String? motherName;
  String? mobileNumber;
  String? maritalStatus;
  String? emergencyMobileNumber;
  String? currentAddress;
  String? permanentAddress;
  String? qualification;
  String? exprience;
  String? ePFNo;
  String? basicSalary;
  String? contract;
  String? location;
  String? bankAccountNumber;
  String? bankAccountName;
  String? bankName;
  String? branchName;
  String? bankIFSCCode;
  String? fbUrl;
  String? twitterUrl;
  String? linkedinUrl;
  String? instraUrl;
  String? resume;
  String? joiningLetter;
}
